const ExperienceSection = () => {
  const experiences = [
    {
      title: "Research Assistant",
      company: "VR Siddhartha Engineering College",
      location: "Vijayawada, India",
      period: "",
      highlights: [
        "Worked on evaluating NLP and language-model outputs across a range of complex prompts and reasoning tasks.",
        "Built Python evaluation pipelines to analyze outputs generated by NLP and LLM models.",
        "Designed benchmark datasets and edge-case prompts for testing model reasoning behavior in realistic settings.",
        "Implemented rubric-based scoring frameworks for grading AI responses across correctness, clarity, and reasoning quality.",
        "Conducted large-scale error analysis across model outputs to identify hallucinations, logical inconsistencies, and retrieval failures.",
        "Developed annotation guidelines used by collaborators to maintain consistent and reproducible output grading.",
      ],
      focusAreas:
        "Focus areas: LLM evaluation · benchmark and edge-case dataset design · rubric-based scoring · hallucination and reasoning analysis · annotation guideline development",
    },
  ];

  const education = {
    degree: "Master of Science in Information Systems",
    school: "Saint Louis University",
    location: "St. Louis, MO",
    gpa: "GPA: 3.90",
  };

  return (
    <section id="experience" className="py-24 px-4 light-section" style={{ backgroundColor: 'hsl(220 10% 96%)' }}>
      <div className="max-w-4xl mx-auto">
        <p className="text-primary font-sans text-sm tracking-[0.3em] uppercase mb-4 text-center">
          Experience
        </p>
        <h2 className="text-3xl md:text-5xl font-serif mb-16 text-center" style={{ color: 'hsl(220 15% 20%)' }}>
          Professional Background
        </h2>

        {/* Work Experience */}
        <div className="mb-16 space-y-12">
          {experiences.map((experience, expIndex) => (
            <div key={expIndex} className={expIndex > 0 ? "pt-8 border-t" : ""} style={expIndex > 0 ? { borderColor: 'hsl(220 10% 85%)' } : {}}>
              <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
                <div>
                  <h3 className="text-2xl font-serif" style={{ color: 'hsl(220 15% 20%)' }}>
                    {experience.title} — {experience.company}
                  </h3>
                  {experience.location && (
                    <p className="text-primary font-medium">{experience.location}</p>
                  )}
                </div>
                <div className="text-right mt-2 md:mt-0">
                  <p style={{ color: 'hsl(220 10% 45%)' }}>{experience.period}</p>
                </div>
              </div>

              <ul className="space-y-3 mb-4">
                {experience.highlights.map((highlight, index) => (
                  <li key={index} className="flex gap-3">
                    <span className="text-primary mt-1.5">•</span>
                    <span className="leading-relaxed" style={{ color: 'hsl(220 10% 45%)' }}>{highlight}</span>
                  </li>
                ))}
              </ul>
              
              {experience.focusAreas && (
                <p className="text-sm font-semibold mt-4" style={{ color: 'hsl(220 15% 20%)' }}>
                  {experience.focusAreas}
                </p>
              )}
            </div>
          ))}
        </div>

        {/* Education */}
        <div className="pt-8 border-t" style={{ borderColor: 'hsl(220 10% 85%)' }}>
          <h3 className="text-xl font-serif mb-6 uppercase tracking-wider" style={{ color: 'hsl(220 15% 20%)' }}>
            Education
          </h3>
          <div className="flex flex-col md:flex-row md:items-center md:justify-between">
            <div>
              <h4 className="text-lg font-serif" style={{ color: 'hsl(220 15% 20%)' }}>
                {education.degree}
              </h4>
              <p className="text-primary font-medium">{education.school}</p>
            </div>
            <div className="text-right mt-2 md:mt-0">
              <p style={{ color: 'hsl(220 10% 45%)' }}>{education.gpa}</p>
              <p style={{ color: 'hsl(220 10% 55%)' }}>{education.location}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ExperienceSection;